### PR TITLE
Various pull request applied and update all dependencies

### PR DESCRIPTION
**Pull request by christiangda**
**List of changest**
* applied PR #6 (manually)
* applied PR #12 (manually)
* applied PR #23 (manually)
* applied PR #32 (manually)
* partial applied PR #29 (Register MDC key for TOPOLOGY_NAME) (manually)
* added Maven Encoding default to properties in pom.xml
* added gitignore rules
* updated all dependencies versions in pom.xml

### CODE REVIEW

**Comment by abshkd** [comment]
no one is maintaining this project anymore, it seems AWWS abandoned storm. I cant find a single working example for Storm 1.x. Any help is appreciated.

**Comment by christiangda** [comment]
Hi @abshkd , yes as you say!, **no one is maintaining this project anymore**, but my PR work with the sample describe here:

https://github.com/awslabs/kinesis-storm-spout/blob/master/src/main/samples/SampleTopology.java

**Comment by pfifer** [comment]
I'm looking into merging this, but don't have an immediate ETA.

**Comment by christiangda** [comment]
Hi pfifer!,  thanks for your help,  The comunity is in nedded.

I'm refactoring my PR, because I'm having problems with curator version, and I Thought that was PR #12

**Comment by christiangda** [comment]
Hi @pfifer and @abshkd I've created a minimal project to test my PR, here you have the link

https://github.com/christiangda/test-kinesis-storm-spout

Regards!

**Comment by christiangda** [comment]
Hi abshkd, yes as you say!, **no one is maintaining this project anymore**, but my PR work with the sample describe here:

https://github.com/awslabs/kinesis-storm-spout/blob/master/src/main/samples/SampleTopology.java

**Comment by abshkd** [comment]
@christiangda You might want to try this instead https://github.com/apache/storm/tree/master/external/storm-kinesis This is better because it matches the curator used in storm. I have it working with very minor issues at the moment. Will post example on Monday.
Edit: Its the same sources btw . only merged with minor changes. Even though the source is in master or 2.x branch you can successfully use it in 1.x. I can confirm that

**Pull request closed without merging**
